services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: scout-keycloak

    command: start-dev

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:
      - "8080:8080"

    volumes:
      - keycloak_data:/opt/keycloak/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  api-gateway:
    build: ./services/api-gateway

    environment:
      APP_ENV: development
      GATEWAY_HOST: 0.0.0.0
      GATEWAY_PORT: 8000

      GATEWAY_AUTH_SERVICE_URL: http://auth-service:8001
      GATEWAY_OPPORTUNITY_SERVICE_URL: http://opportunity-service:8002
      GATEWAY_INGESTION_SERVICE_URL: http://ingestion-service:8003
      GATEWAY_NOTIFICATION_SERVICE_URL: http://notification-service:8004

      REDIS_URL: ${REDIS_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      LOG_LEVEL: ${LOG_LEVEL}
      CORS_ORIGINS: ${CORS_ORIGINS}

    ports:
      - "8000:8000"

    depends_on:
      - auth-service
      - opportunity-service
      - ingestion-service
      - notification-service
      - redis
      - rabbitmq

  auth-service:
    build: ./services/auth-service
    environment:
      APP_ENV: development
      DATABASE_URL: ${AUTH_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "8001:8001"
    depends_on:
      - redis

  opportunity-service:
    build: ./services/opportunity-service
    environment:
      APP_ENV: development
      OPPORTUNITY_DATABASE_URL: ${OPPORTUNITY_DATABASE_URL}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      REDIS_URL: ${REDIS_URL}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "8002:8002"
    depends_on:
      - redis
      - elasticsearch

  ingestion-service:
    build: ./services/ingestion-service
    environment:
      APP_ENV: development
      INGESTION_DATABASE_URL: ${INGESTION_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      OPPORTUNITY_SERVICE_URL: http://opportunity-service:8002
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "8003:8003"
    depends_on:
      - rabbitmq
      - opportunity-service

  notification-service:
    build: ./services/notification-service
    environment:
      APP_ENV: development
      DATABASE_URL: ${NOTIFICATION_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "8004:8004"
    depends_on:
      - rabbitmq

volumes:
  keycloak_data: